//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MappingBJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class mmdestination
    {
        public int ID { get; set; }
        public string Key { get; set; }
        public string DName { get; set; }
        public string DAdd1 { get; set; }
        public string DAdd2 { get; set; }
        public string DCity { get; set; }
        public string DProv { get; set; }
        public string DCty { get; set; }
        public string DPostal { get; set; }
        public string DContact { get; set; }
        public string Pcs { get; set; }
        public string Pwgt { get; set; }
        public string Twgt { get; set; }
        public string Tskid { get; set; }
        public string UOM { get; set; }
        public string Dim { get; set; }
        public string Cube { get; set; }
        public string Ref1 { get; set; }
        public string Ref2 { get; set; }
        public string Ref3 { get; set; }
        public string OName { get; set; }
        public string OAdd1 { get; set; }
        public string OAdd2 { get; set; }
        public string OCity { get; set; }
        public string OProv { get; set; }
        public string OCty { get; set; }
        public string OPostal { get; set; }
        public string PuDate__yy_mm_dd_ { get; set; }
        public string DelDate__yy_mm_dd_ { get; set; }
        public string Hand_Notes { get; set; }
        public string Special_Instructions { get; set; }
    }
}
