//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MappingBJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class mmraw
    {
        public int ID { get; set; }
        public string TRACKING_NUMBER__REF { get; set; }
        public string SHIP_DATE { get; set; }
        public string ACCOUNT_NUMBER { get; set; }
        public string CODE { get; set; }
        public string SHIPPER_NAME { get; set; }
        public string SHIPPER_ADDRESS { get; set; }
        public string SPACER1 { get; set; }
        public string SHIPPER_CITY { get; set; }
        public string SHIPPER_PROVINCE { get; set; }
        public string SHIPPER_POSTAL { get; set; }
        public string CONSIGNEE_NAME { get; set; }
        public string KEY_CONSIGNEE_NUMBER { get; set; }
        public string CONSIGNEE { get; set; }
        public string CONSIGNEE_LOCATION { get; set; }
        public string CONSIGNEE_ADDRESS_1 { get; set; }
        public string CONSIGNEE_ADDRESS_2 { get; set; }
        public string CONSIGNEE_CITY { get; set; }
        public string CONSIGNEE_PROVINCE { get; set; }
        public string CONSIGNEE_POSTAL { get; set; }
        public string SPACER2 { get; set; }
        public string SPACER3 { get; set; }
        public string SKID_COUNT { get; set; }
        public string WEIGHT { get; set; }
        public string SERVICE { get; set; }
        public string TRACKING_NUMBER { get; set; }
        public string DEL_INSTRUCTIONS { get; set; }
        public string ACC_ { get; set; }
        public string ACC_2 { get; set; }
        public string ACC_3 { get; set; }
    }
}
