//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MappingBJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class mmref
    {
        public int ID { get; set; }
        public string Store { get; set; }
        public string Vendor { get; set; }
        public string Store_Name { get; set; }
        public string Name { get; set; }
        public string Address_1 { get; set; }
        public string Address_2 { get; set; }
        public string City { get; set; }
        public string Prov { get; set; }
        public string PC { get; set; }
        public string All_year_Daily_Deliveries { get; set; }
        public string Start_Window { get; set; }
        public string End_Window { get; set; }
        public string Length_of_Window { get; set; }
        public string Tailgate_Dock { get; set; }
        public string Email { get; set; }
        public string Attention { get; set; }
        public string Phone_ { get; set; }
        public string Q4_Skid_Max { get; set; }
        public string Q4_Est_Cartons_Peak { get; set; }
        public string Q4_Weekly_Max_Carton { get; set; }
        public string Rest_of_Year_Skid_Max { get; set; }
        public string Rest_of_Year_Est__Cartons_Off_Peak { get; set; }
        public string Off_Peak_Max_Carton { get; set; }
        public string Carrier { get; set; }
        public string Transit_Days { get; set; }
        public string Ship_Monday { get; set; }
        public string Ship_Tuesday { get; set; }
        public string Ship_Wednesday { get; set; }
        public string Ship_Thursday { get; set; }
        public string Ship_Friday { get; set; }
        public string Skid_Reduction { get; set; }
        public string Online_or_Offline { get; set; }
        public string Notes { get; set; }
    }
}
